resolver: lts-13.2
allow-newer: true
flags:
  ble:
    hasDBus: true
extra-package-dbs: []
packages:
- '.'
- location:
    git: 'https://github.com/afcady/d-bus/'
    commit: '2dd54818eca2a2af9a9688f648d00cc1325df838'
  extra-dep: true
extra-deps:
